### ISSUE TITLE
Troubleshoot no blinking LED?

### ISSUE THREAD

**Issue by cjsavoia** [mongoose-os-apps/mel-ac-homekit#11]
I have unit MLZ-KY06NA (ceiling cassette w/ CN105). Flashed mel-ac-homekit to an ESP8266 and wired to CN105 according to MEL-AC. Paired to wifi and successfully added to homekit. 

I am not seeing the LED blink when changing parameters. Actually not seeing it blink at all. Is there troubleshooting steps to determine where to go next?

**Comment by cjsavoia** [comment]
The solution was to change uart to O in mos.yml file and then rebuild. Leaving issue open until Readme is updated

**Comment by d4rkmen** [comment]
hi, I am glad you have solved the problem. Ofcourse there are different boards with differfent pinouts for UART. There is why we use mongoose config service.
To change any setting just call: `mos config-set mel-ac.uart_no=0` and dont need to recompile and\or reflash

**Comment by cjsavoia** [comment]
Thats great to know. I saw another issue that was fixed by changing the UART #. I would recommend to add a small note in the README. Closing issue now. Thanks!
