### ISSUE TITLE
Possible to use a remote temperature sensor to reduce short cycle? 

### ISSUE THREAD

**Issue by cjsavoia** [mongoose-os-apps/mel-ac-homekit#12]
In MEL-AC library, there is a command to set external temperature value. `mgos_mel_ac_set_ext_temp(float temp);` Is it possible to read data from Homekit (ie homepod in same room) and use value to set above command? 

Mistubishi units are known to short-cycle, where the unit turns on/off many times and uses more power. A common fix is to use the MHK2 thermostat or other remote thermostat, placed far from the unit. But MHK2 is expensive and does not allow daisy-chain to other CN105 connectors.

**Comment by d4rkmen** [comment]
External in this conext means extarnal device can update temperature value on MEL-AC device. Unfortunately, interaction with another homekit accessory is not a part of homekit spec.

**Comment by naanlizard** [comment]
Would it be possible to add a temperature sensor to the esp8266 board and use that to replace the temp sensor?

Or poll an http address or something?

As an example, see what this project is doing:

https://github.com/geoffdavis/esphome-mitsubishiheatpump?tab=readme-ov-file#remote-temperature

EDIT: to add, the reason I would prefer that be integrated here, is I don't want to set up a bridge to go from ESPhome->homekit, I just want to have an ESP8266 connected to the AC and it directly provides the correct homekit integration. This project seems the best bet for that

**Comment by cjsavoia** [comment]
I see that Eve has released a matter-protocol device that directly communicates between controller and sensor (albeit, for radiators). So sounds like a project like "mel-ac-matter" would theoretically allow a remote sensor to work. Some idea for the future! 

https://www.evehome.com/en-us/eve-thermo-control

**Comment by d4rkmen** [comment]
fyi, the temp sensor is locating inside incoming air chamber (in ducted internal unit)
so the temperature measured by incoming airflow
