### ISSUE TITLE
`ModeFanService` and `ModeDryService` switch names not set

### ISSUE THREAD

**Issue by mtrezza** [mongoose-os-apps/mel-ac-homekit#13]
The switches for `ModeFanService` and `ModeDryService` are titled "Switch" and "Switch 2" in the Apple Home app. It appears that the names are not properly set, hence they receive default names.
```
[Jul 14 12:15:48.938] HAPPlatformLog.c:55     Characteristic [0000000000000001 MEL-D7E4] [0000000000000232 name] Calling read handler.
[Jul 14 12:15:48.938] HAPPlatformLog.c:55     RequestHandlers Sending service name: "Wide vane".
```

**Comment by d4rkmen** [comment]
After some iOS update, predefined service names are no longer used. Its always getting default names. And this happend to all HomeKit apps, not only Apple Home
