### ISSUE TITLE
Add support for Vane and Wide Vane

### ISSUE THREAD

**Issue by mtrezza** [mongoose-os-apps/mel-ac-homekit#14]
Add support for Vane and Wide Vane; it seems to be prepared in code, but says:

> (not visible in Home App yet, use Eve) control up-down vane

What's missing to support it in HomeKit? Is it a HomeKit limitation or just needs to be implemented in code?

**Comment by d4rkmen** [comment]
Its up to Apple what controls they want to add in Home App
Actual services are working for
moth vanes, but not visible in the app

**Comment by mtrezza** [comment]
Wouldn't it be possible to add slider controls for vane tilting? Similar to how blinds are tilted:
<img width="184" alt="image" src="https://github.com/mongoose-os-apps/mel-ac-homekit/assets/5673677/94ef614b-9bcd-4d42-b73e-a2fb884f2500">

**Comment by rcarmo** [comment]
Not unless you surfaced an extra bogus device that exposed that control. Apple's Home app only exposes a portion of the HomeKit device characteristics, and for thermostats they only expose what you see currently.

**Comment by d4rkmen** [comment]
![image](https://github.com/user-attachments/assets/4b605b56-acc3-4029-b12c-600af5d1da0e)
Check your device under Eve app and you will see vanes

**Comment by mtrezza** [comment]
Yes, in the Eve app I indeed see them. Thanks for clarifying
