### ISSUE TITLE
Add support for reading AC status

### ISSUE THREAD

**Issue by mtrezza** [mongoose-os-apps/mel-ac-homekit#15]
When asking Siri

> What's the status of the AC?

it responds with

> Sorry, I don't what mode it's in right now.

HomeKit should be able to read the AC state for automation.

**Comment by d4rkmen** [comment]
Ask this way: status of thermostat in **room_name**

**Comment by mtrezza** [comment]
That only works while the AC is on:

- Turn the thermostat on.
(waiting 10 seconds)
- Status of thermostat?
-- The thermostat is cooling to 25°C.

But when the AC is off, it doesn't seem to know whether it's on or off:

- Turn the thermostat off.
(waiting 10 seconds)
- Status of thermostat.
-- Sorry, I don't what mode it's in right now.

Interestingly, in the Home app I see the thermostat is "off". So not sure whether I need to rephrase the question or whether this is a bug in HomeKit.

**Comment by d4rkmen** [comment]
This is al about HomeKit framework and Siri itself. The acessory provides all data according to HAP spec.
