### ISSUE TITLE
Compatible models

### ISSUE THREAD

**Issue by Nickulous** [mongoose-os-apps/mel-ac-homekit#2]
What models does this plugin supports? Does it support MSZ-EF25VA for example ?

**Comment by d4rkmen** [comment]
Hi, there are compatibility tables by links no the [mel-ac](https://github.com/mongoose-os-libs/mel-ac) library readme.
It seems your model is supported

**Comment by Nickulous** [comment]
> Hi, there are compatibility tables by links no the [mel-ac](https://github.com/mongoose-os-libs/mel-ac) library readme. It seems your model is supported

Thanks!
