### ISSUE TITLE
Does this work with heat pumps from Mitsubishi?

### ISSUE THREAD

**Issue by woodsbox** [mongoose-os-apps/mel-ac-homekit#7]
HI!

Does this also work with heat pumps from Mitsubishi?

Kind regards

**Comment by d4rkmen** [comment]
hi, yes
compatibility links are in readme

**Comment by woodsbox** [comment]
Are you at discord or something where I can chat with you? :)

**Comment by woodsbox** [comment]
I did a install a while ago with a shelly but I do not understand how to do this install? I assume this can be installed on the wifi module from mitsubishi?

**Comment by woodsbox** [comment]
Like is it suitable with the: MAC-587IF-E?

**Comment by woodsbox** [comment]
@d4rkmen you allright?

**Comment by d4rkmen** [comment]
hi, still alive, thanks
this unit made to replace original MAC-xxxx device
U have to connect it using CM-105 plug

**Comment by woodsbox** [comment]
@d4rkmen  Is there a way you can help me (a noob) or can I chat with you because I really want to use this :)

**Comment by wazzapnz** [comment]
Hi - did you end up resolving this @woodsbox?

I have a basic question - can you flash this onto a Shelly and then replace the official Mitsubishi unit? Would I then wire the Shelly to the plug?  And then the Shelly would replace that Mitsubishi unit?

Is there anyway to just log in through MELCloud?

**Comment by d4rkmen** [comment]
@woodsbox hi, what exactly are you missing in the project? Shelly can work, in theory. The mitsubishi original unit is cloud based solution. It queries the device status every minute and control it bu predefined shedule.
This project gives you absolute freedon - voice control, any automations with Home App etc.

**Comment by d4rkmen** [comment]
@wazzapnz - no, its not a clone of MELCloud device, it just uses the same communication port CN105. You cant replace it and expect it will connect MELCloud.
Actually, strange, if you need (so much limited) MELCloud expirience, just use original MAC IF device

**Comment by wazzapnz** [comment]
> @wazzapnz - no, its not a clone of MELCloud device, it just uses the same communication port CN105. You cant replace it and expect it will connect MELCloud.
> Actually, strange, if you need (so much limited) MELCloud expirience, just use original MAC IF device

Thanks @d4rkmen - much appreciated.  Basically it replaces the original MAC IF device which I understand and the extra functionality seems to be well worth it.

I'm happy to lose my existing device, but am at another stop point...

Can you please send me a link to the plug that I need?  Also - how do I know which pins of the shelly to wire to the plug?

**Comment by d4rkmen** [comment]
You can get components and to crimp the connector by yourself:
[JST PAP-05V-S housing](https://www.digikey.com/product-detail/en/jst-sales-america-inc/PAP-05V-S/455-1489-ND/759977)
[JST SPHD-002T-P0.5 contacts](https://www.digikey.com/product-detail/en/jst-sales-america-inc/SPHD-002T-P0.5/455-1313-1-ND/608809)
or find ready `pigtails` on market
